# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cygdrive/c/users/ruurdw/documents/github/Coy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cygdrive/c/users/ruurdw/documents/github/Coy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/users/ruurdw/documents/github/Coy/CMakeFiles /cygdrive/c/users/ruurdw/documents/github/Coy/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/users/ruurdw/documents/github/Coy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named demo1.txt

# Build rule for target.
demo1.txt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 demo1.txt
.PHONY : demo1.txt

# fast build rule for target.
demo1.txt/fast:
	$(MAKE) -f CMakeFiles/demo1.txt.dir/build.make CMakeFiles/demo1.txt.dir/build
.PHONY : demo1.txt/fast

#=============================================================================
# Target rules for targets named demo2.txt

# Build rule for target.
demo2.txt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 demo2.txt
.PHONY : demo2.txt

# fast build rule for target.
demo2.txt/fast:
	$(MAKE) -f CMakeFiles/demo2.txt.dir/build.make CMakeFiles/demo2.txt.dir/build
.PHONY : demo2.txt/fast

#=============================================================================
# Target rules for targets named joy

# Build rule for target.
joy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 joy
.PHONY : joy

# fast build rule for target.
joy/fast:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/build
.PHONY : joy/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named run.c

# Build rule for target.
run.c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run.c
.PHONY : run.c

# fast build rule for target.
run.c/fast:
	$(MAKE) -f CMakeFiles/run.c.dir/build.make CMakeFiles/run.c.dir/build
.PHONY : run.c/fast

eval.o: eval.c.o

.PHONY : eval.o

# target to build an object file
eval.c.o:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/eval.c.o
.PHONY : eval.c.o

eval.i: eval.c.i

.PHONY : eval.i

# target to preprocess a source file
eval.c.i:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/eval.c.i
.PHONY : eval.c.i

eval.s: eval.c.s

.PHONY : eval.s

# target to generate assembly for a file
eval.c.s:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/eval.c.s
.PHONY : eval.c.s

lexer.o: lexer.c.o

.PHONY : lexer.o

# target to build an object file
lexer.c.o:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/lexer.c.o
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/lexer.c.o
.PHONY : lexer.c.o

lexer.i: lexer.c.i

.PHONY : lexer.i

# target to preprocess a source file
lexer.c.i:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/lexer.c.i
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/lexer.c.i
.PHONY : lexer.c.i

lexer.s: lexer.c.s

.PHONY : lexer.s

# target to generate assembly for a file
lexer.c.s:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/lexer.c.s
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/lexer.c.s
.PHONY : lexer.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/main.c.s
.PHONY : main.c.s

memory.o: memory.c.o

.PHONY : memory.o

# target to build an object file
memory.c.o:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/memory.c.o
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/memory.c.o
.PHONY : memory.c.o

memory.i: memory.c.i

.PHONY : memory.i

# target to preprocess a source file
memory.c.i:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/memory.c.i
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/memory.c.i
.PHONY : memory.c.i

memory.s: memory.c.s

.PHONY : memory.s

# target to generate assembly for a file
memory.c.s:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/memory.c.s
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/memory.c.s
.PHONY : memory.c.s

node.o: node.c.o

.PHONY : node.o

# target to build an object file
node.c.o:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/node.c.o
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/node.c.o
.PHONY : node.c.o

node.i: node.c.i

.PHONY : node.i

# target to preprocess a source file
node.c.i:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/node.c.i
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/node.c.i
.PHONY : node.c.i

node.s: node.c.s

.PHONY : node.s

# target to generate assembly for a file
node.c.s:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/node.c.s
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/node.c.s
.PHONY : node.c.s

parse.o: parse.c.o

.PHONY : parse.o

# target to build an object file
parse.c.o:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/parse.c.o
.PHONY : parse.c.o

parse.i: parse.c.i

.PHONY : parse.i

# target to preprocess a source file
parse.c.i:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/parse.c.i
.PHONY : parse.c.i

parse.s: parse.c.s

.PHONY : parse.s

# target to generate assembly for a file
parse.c.s:
	$(MAKE) -f CMakeFiles/joy.dir/build.make CMakeFiles/joy.dir/parse.c.s
.PHONY : parse.c.s

run.o: run.c.o

.PHONY : run.o

# target to build an object file
run.c.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/run.c.o
.PHONY : run.c.o

run.i: run.c.i

.PHONY : run.i

# target to preprocess a source file
run.c.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/run.c.i
.PHONY : run.c.i

run.s: run.c.s

.PHONY : run.s

# target to generate assembly for a file
run.c.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/run.c.s
.PHONY : run.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... demo2.txt"
	@echo "... demo1.txt"
	@echo "... run.c"
	@echo "... run"
	@echo "... joy"
	@echo "... eval.o"
	@echo "... eval.i"
	@echo "... eval.s"
	@echo "... lexer.o"
	@echo "... lexer.i"
	@echo "... lexer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... memory.o"
	@echo "... memory.i"
	@echo "... memory.s"
	@echo "... node.o"
	@echo "... node.i"
	@echo "... node.s"
	@echo "... parse.o"
	@echo "... parse.i"
	@echo "... parse.s"
	@echo "... run.o"
	@echo "... run.i"
	@echo "... run.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

