/*
    module  : mktime.c
    version : 1.10
    date    : 06/21/22
*/
#ifndef MKTIME_C
#define MKTIME_C

/**
1720  mktime  :  DA	T  ->  I
Converts a list T representing local time into a time I.
T is in the format generated by localtime.
*/
void decode_time(struct tm *t)
{
    int i;
    Stack *list;

    LIST;
    memset(t, 0, sizeof(struct tm));
    list = (Stack *)GET_AS_LIST(stack[-1]);
    i = vec_size(list);
    t->tm_year = GET_AS_INTEGER(vec_at(list, --i)) - 1900;
    t->tm_mon = GET_AS_INTEGER(vec_at(list, --i)) - 1;
    t->tm_mday = GET_AS_INTEGER(vec_at(list, --i));
    t->tm_hour = GET_AS_INTEGER(vec_at(list, --i));
    t->tm_min = GET_AS_INTEGER(vec_at(list, --i));
    t->tm_sec = GET_AS_INTEGER(vec_at(list, --i));
    t->tm_isdst = GET_AS_BOOLEAN(vec_at(list, --i));
    t->tm_yday = GET_AS_INTEGER(vec_at(list, --i));
    t->tm_wday = GET_AS_INTEGER(vec_at(list, --i));
}

void do_mktime(void)
{
    struct tm t;

    COMPILE;
    ONEPARAM;
    decode_time(&t);
    stack[-1] = MAKE_INTEGER(mktime(&t));
}
#endif
