/*
    module  : mktime.c
    version : 1.9
    date    : 01/19/20
*/
#ifndef MKTIME_C
#define MKTIME_C

void decode_time(struct tm *t)
{
    int i;
    Stack *List;

    memset(t, 0, sizeof(struct tm));
    if ((List = (Stack *)stack[-1]) == 0)
	return;
    i = vec_size(List);
    t->tm_year = vec_at(List, --i) - 1900;
    t->tm_mon = vec_at(List, --i) - 1;
    t->tm_mday = vec_at(List, --i);
    t->tm_hour = vec_at(List, --i);
    t->tm_min = vec_at(List, --i);
    t->tm_sec = vec_at(List, --i);
    t->tm_isdst = vec_at(List, --i);
    t->tm_yday = vec_at(List, --i);
    t->tm_wday = vec_at(List, --i);
}

/**
mktime  :  T  ->  I
Converts a list T representing local time into a time I.
T is in the format generated by localtime.
*/
void do_mktime(void)
{
    struct tm t;

    UNARY;
    decode_time(&t);
    stack[-1] = mktime(&t);
}
#endif
